name: blast_env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blast=2.17.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - curl=8.17.0
  - entrez-direct=24.0
  - gettext=0.21.0
  - icu=73.1
  - jansson=2.14
  - libcurl=8.17.0
  - libev=4.33
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=1.3
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncbi-vdb=3.3.0
  - ncurses=6.5
  - openssl=3.0.18
  - pcre2=10.46
  - perl=5.32.1
  - perl-archive-tar=3.04
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.214
  - perl-compress-raw-zlib=2.214
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.214
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.04
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - wget=1.25.0
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /home/kmrozik/.conda/envs/blast_env
